version: '2'
 
services:
  mysql:
    image: mysql:8
    container_name: grocery-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "gracy_root"
      MYSQL_DATABASE: groceries
      MYSQL_USER: gracy
      MYSQL_PASSWORD: gracyspw